env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  alias_length: 5
  user: "myuser"
  password: "secret"
kafka:
  username: "Maxim"   # currently not used
  password: "secret"  # currently not used
  bootstrap_server: "localhost:9092"
